package example

object Hello extends Greeting with App {

  def printGreetings() {
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(greeting)
    println(1+0)
    println(1+0)
  }

  def printGreetings2() {
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(1+0)
    println(greeting)
    println(greeting)
    println(1+0)
    println(1+0)
  }


  printGreetings()
}

trait Greeting {
  lazy val greeting: String = "hello"
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")
  println("CIAONE ANGELONE")

}
